name: demo
description: demo App

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.24+29

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  algolia: # ^0.1.7
    git: https://github.com/kdy1/dart_algolia.git
  after_init: ^0.1.2
  apple_sign_in: ^0.1.0
  async: ^2.4.2

  bloc: ^6.0.3 #^3.0.0

  cloud_firestore: ^0.14.0+2 #^0.13.4+2
  cloud_functions: ^0.6.0 #^0.4.2+3
  cached_network_image: ^2.3.2+1 #^2.0.0
  country_icons: ^1.1.1
  country_pickers:
    git:
      url: https://github.com/crtl/country_pickers
      ref: option-popOnPick

  devicelocale: ^0.3.2 #^0.2.2

  easy_web_view: ^1.3.0
  equatable: ^1.2.5 #^1.0.3
  email_validator: ^1.0.5
  event_bus: ^1.1.1

  firebase_core: ^0.5.0 #^0.4.3+3
  firebase_auth: ^0.18.0+1 #^0.15.4
  firebase_storage: ^4.0.1 #^3.1.3
  firebase_crashlytics: ^0.2.0 #^0.1.3
  firebase_messaging: ^7.0.0 #^6.0.13
  firebase_analytics: ^6.0.0 #^5.0.11
  flare_flutter: ^2.0.3
  firebase_dynamic_links: ^0.6.0 #^0.5.0+11
  flutter_local_notifications: ^1.4.4+4 #^1.3.0
  flutter_signin_button: ^1.1.0 #^1.0.0
  flutter_bloc: ^6.0.5 #^3.2.0
  flutter_parsed_text: ^1.2.4
  file_picker: ^2.0.1+1 #^1.4.3+2
  freezed_annotation: ^0.12.0 #^0.11.0
  flutter_facebook_login: ^3.0.0
  facebook_app_events: ^0.6.0 #^0.7.0 #^0.6.0
  font_awesome_flutter: ^8.8.1
  flushbar:
    git:
      url: https://github.com/AndreHaueisen/flushbar
      ref: master

  google_sign_in: ^4.5.4 #^4.1.1

  intl: 0.16.1
  intl_translation: ^0.17.10+1 #^0.17.9
  image_picker: ^0.6.7+11 #^0.6.7+1
  image_cropper: ^1.3.1 #^1.2.3

  json_annotation: ^3.1.0 #^3.0.1

  language_pickers:
    git:
      url: https://github.com/crtl/flutter_language_pickers.git
      ref: remove-alpha2-iso-code


  meta: #^1.2.3 #^1.1.8

  # video_compress: ^2.0.0
  package_info: ^0.4.3 #^0.4.1
  path_provider: ^1.6.18 #^1.6.5
  path: ^1.6.4
  provider: ^4.3.2+2 #^4.0.2
  preload_page_view: 0.1.4

  rxdart: ^0.24.1 #^0.23.1

  share: ^0.6.5+2 #^0.6.3+6
  shared_preferences: ^0.5.12 #^0.5.8
  sqflite: ^1.3.1+1 #^1.3.0

  table_calendar: ^2.2.2
  toast: ^0.1.5

  uuid: ^2.2.2 #^2.0.0
  url_launcher: ^5.7.1 #^5.4.1

  video_compress:
    git:
      url: https://github.com/crtl/VideoCompress.git
      ref: refactor-compress-progress
  video_player: ^0.11.0 #^0.10.12+2
  video_thumbnail: ^0.2.1

  wakelock: ^0.1.4+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: ^1.14.4
  build_runner:
  icapps_license: ^0.0.6
  json_serializable: ^3.2.5
  freezed: ^0.12.1 #^0.11.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/social_icons/
    - assets/videos/
    - assets/i18n/
    - assets/flare/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
    - family: ChallengeIcons
      fonts:
        - asset: assets/fonts/ChallengeIcons.ttf

    - family: NunitoSans
      fonts:
        - asset: assets/fonts/Nunito_Sans/NunitoSans-Light.ttf
        - asset: assets/fonts/Nunito_Sans/NunitoSans-Regular.ttf
        - asset: assets/fonts/Nunito_Sans/NunitoSans-SemiBold.ttf
        - asset: assets/fonts/Nunito_Sans/NunitoSans-Bold.ttf
        - asset: assets/fonts/Nunito_Sans/NunitoSans-ExtraBold.ttf

    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu/Ubuntu-Light.ttf
        - asset: assets/fonts/Ubuntu/Ubuntu-Regular.ttf
        - asset: assets/fonts/Ubuntu/Ubuntu-RegularItalic.ttf
          style: italic
        - asset: assets/fonts/Ubuntu/Ubuntu-Bold.ttf
          weight: 700

    - family: Merriweather Sans
      fonts:
        - asset: assets/fonts/Merriweather_Sans/MerriweatherSans-Light.ttf
        - asset: assets/fonts/Merriweather_Sans/MerriweatherSans-Regular.ttf
        - asset: assets/fonts/Merriweather_Sans/MerriweatherSans-RegularItalic.ttf
          style: italic
        - asset: assets/fonts/Merriweather_Sans/MerriweatherSans-Bold.ttf
          weight: 700
    - family: Robot_Mono
      fonts:
        - asset: assets/fonts/Roboto_Mono/RobotoMono-VariableFont_wght.ttf
          weight: 400

    - family: Lemon_Milk
      fonts:
        - asset: assets/fonts/Lemon_Milk/LEMONMILK-Bold.otf
          weight: 600
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

#dependency_overrides:
#  analyzer: '0.39.14'
